### ISSUE TITLE
Error "You are not authenticated" after exiting test mode

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio-dashboard#254]
**Describe the bug**
After leaving test mode in the dashboard (toggling the test mode switch to off), the shipments load for a long time. The shipments get displayed eventually, but there are error messages popping up in the docker logs.

**To Reproduce**
1. Go to the dashboard and select "Shipments".
2. Enable test mode. Test data is loading successfully.
3. Disable test mode again. Loading bar is being displayed, docker logs show errors.
4. Shipments still get displayed eventually after some time. Logout and new login does not help though.

**Expected behavior**
Switching test mode on/off should be smooth and without errors.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 2023.1.12

**Additional context**

Docker log:

```
karrio.api        | GraphQL request:2:3
karrio.api        | 1 | query GetUser {
karrio.api        | 2 |   user {
karrio.api        |   |   ^
karrio.api        | 3 |     email
karrio.api        | You are not authenticated
karrio.api        | 
karrio.api        | GraphQL request:2:3
karrio.api        | 1 | query get_shipments($filter: ShipmentFilter) {
karrio.api        | 2 |   shipments(filter: $filter) {
karrio.api        |   |   ^
karrio.api        | 3 |     page_info {
karrio.api        | Traceback (most recent call last):
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/graphql/execution/execute.py", line 521, in execute_field
karrio.api        |     result = resolve_fn(source, info, **args)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 552, in _resolver
karrio.api        |     return _get_result_with_extensions(_source, strawberry_info, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 526, in _get_result
karrio.api        |     return field.get_result(
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/strawberry/field.py", line 178, in get_result
karrio.api        |     return self.base_resolver(*args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/strawberry/types/fields/resolver.py", line 187, in __call__
karrio.api        |     return self.wrapped_func(*args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/karrio/server/graph/utils.py", line 95, in wrapper
karrio.api        |     raise exceptions.AuthenticationFailed(
karrio.api        | rest_framework.exceptions.AuthenticationFailed: You are not authenticated
karrio.api        | Stack (most recent call last):
karrio.api        |   File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
karrio.api        |     self._bootstrap_inner()
karrio.api        |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
karrio.api        |     self.run()
karrio.api        |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
karrio.api        |     self._target(*self._args, **self._kwargs)
karrio.api        |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
karrio.api        |     work_item.run()
karrio.api        |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
karrio.api        |     result = self.fn(*self.args, **self.kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
karrio.api        |     return func(*args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
karrio.api        |     response = response or self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/whitenoise/middleware.py", line 124, in __call__
karrio.api        |     return self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
karrio.api        |     response = response or self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
karrio.api        |     response = response or self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
karrio.api        |     response = response or self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
karrio.api        |     response = response or self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
karrio.api        |     response = response or self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django_otp/middleware.py", line 32, in __call__
karrio.api        |     return self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
karrio.api        |     response = response or self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
karrio.api        |     response = response or self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
karrio.api        |     response = get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/karrio/server/core/middleware.py", line 40, in __call__
karrio.api        |     response = self.get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/asgiref/sync.py", line 218, in __call__
karrio.api        |     current_executor.run_until_future(loop_future)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 62, in run_until_future
karrio.api        |     work_item.run()
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
karrio.api        |     result = self.fn(*self.args, **self.kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
karrio.api        |     return func(*args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
karrio.api        |     return view_func(*args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
karrio.api        |     return self.dispatch(request, *args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/karrio/server/graph/views.py", line 36, in dispatch
karrio.api        |     return super().dispatch(request, *args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/karrio/server/core/authentication.py", line 183, in dispatch
karrio.api        |     return super().dispatch(request, *args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
karrio.api        |     return bound_method(*args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
karrio.api        |     return view_func(*args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/strawberry/django/views.py", line 231, in dispatch
karrio.api        |     result = self.schema.execute_sync(
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/strawberry/schema/schema.py", line 264, in execute_sync
karrio.api        |     result = execute_sync(
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/strawberry/schema/execute.py", line 249, in execute_sync
karrio.api        |     process_errors(result.errors, execution_context)
karrio.api        | ERROR views.py 49 You are not authenticated
karrio.api        | 
karrio.api        | GraphQL request:2:3
karrio.api        | 1 | query get_shipments($filter: ShipmentFilter) {
karrio.api        | 2 |   shipments(filter: $filter) {
karrio.api        |   |   ^
karrio.api        | 3 |     page_info {
```
(That's it. Log ending after this line)

**Comment by MarcoWel** [comment]
Addition: Now it happens the other way around: When entering test mode, above error appears, when exiting test mode, everything is fine.

When the error occurs, a page refresh helps getting the shipments displayed despite the error.

**Comment by MarcoWel** [comment]
@danh91 Did you have a chance to look into this? Still present with 2023.3.4
